project_id = "wjuoghoahuyxvascddak"

[functions.validate-answer]
verify_jwt = false

[functions.generate-session-analysis]
verify_jwt = false

[functions.generate-lesson]
verify_jwt = false

[functions.tutor-chat]
verify_jwt = false

[functions.generate-lesson-bulk]
verify_jwt = false

[functions.generate-single-lesson]
verify_jwt = false
